import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import CustomHead from './components/head';
import Script from 'next/script';
import ToastProvider from './components/Toast/ToastContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CustomHead />
      <body>
        {' '}
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
