name: .NET

on:
  push:
    branches: [ "deploy-app" ]
  pull_request:
    branches: [ "deploy-app" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Back-End/IntelliView
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Back-End/IntelliView
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Back-End/IntelliView
